apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BootCampProjects
  annotations:
    github.com/project-slug: tsaxena2/BootCampProjects
spec:
  type: other
  lifecycle: unknown
  owner: guests
